application: wordbox
version: 0-1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
  secure: always

- url: /.*
  static_dir: static
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
