application: wordbox-app
version: 0-1
runtime: go
api_version: go1

handlers:
# Endpoints
- url: /_ah/spi/.*
  script: _go_app

- url: /.*
  static_dir: static
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
